apiVersion: apps/v1
kind: Deployment
metadata:
  name: fullstack-blogging-app
  labels:
    app: fullstack-blogging-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fullstack-blogging-app
  template:
    metadata:
      labels:
        app: fullstack-blogging-app
    spec:
      containers:
      - name: fullstack-blogging-app
        image: ningarajgani/fullstack-blogging-app:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "prod"
        - name: DB_URL
          value: "jdbc:postgresql://db.ziatzkjwpuxlgrzwbalc.supabase.co:5432/postgres"
        - name: DB_USERNAME
          value: "postgres"
        - name: DB_PASSWORD
          value: "NINGU6361@n"
        - name: SUPABASE_ANON_KEY
          value: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InppYXR6a2p3cHV4bGdyendiYWxjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njc5NDU0MTIsImV4cCI6MjA4MzUyMTQxMn0.QXgNrpu8NWu48OoDmwTPjAQFgV5u9k0bzULh5YHgY9s"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /login
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /login
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
      imagePullSecrets:
        - name: regcred

---
apiVersion: v1
kind: Service
metadata:
  name: fullstack-blogging-app-service
  labels:
    app: fullstack-blogging-app
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    app: fullstack-blogging-app

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  application.properties: |
    spring.application.name=twitter-app
    spring.datasource.url=jdbc:postgresql://db.ziatzkjwpuxlgrzwbalc.supabase.co:5432/postgres
    spring.datasource.username=postgres
    spring.datasource.password=NINGU6361@n
    spring.datasource.driverClassName=org.postgresql.Driver
    spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
    spring.jpa.hibernate.ddl-auto=update
    supabase.url=https://ziatzkjwpuxlgrzwbalc.supabase.co
    supabase.anon.key=${SUPABASE_ANON_KEY}
    spring.thymeleaf.cache=true
