spring.application.name=twitter-app

# Supabase (PostgreSQL) Connection Settings
spring.datasource.url=jdbc:postgresql://db.ziatzkjwpuxlgrzwbalc.supabase.co:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=NINGU6361@n
spring.datasource.driverClassName=org.postgresql.Driver

# JPA/Hibernate properties
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Supabase API Settings
supabase.url=https://ziatzkjwpuxlgrzwbalc.supabase.co
supabase.anon.key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InppYXR6a2p3cHV4bGdyendiYWxjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njc5NDU0MTIsImV4cCI6MjA4MzUyMTQxMn0.QXgNrpu8NWu48OoDmwTPjAQFgV5u9k0bzULh5YHgY9s

# Thymeleaf
spring.thymeleaf.cache=false